FROM ubuntu:22.04

RUN apt-get update -y

RUN apt-get install -y python3-pip curl

RUN apt-get install -y clang-format-14 clang clang-tidy git gcc g++ make

RUN curl -o cmake.sh -L "https://github.com/Kitware/CMake/releases/download/v3.25.2/cmake-3.25.2-linux-x86_64.sh"; \
    chmod +x cmake.sh; \
    ./cmake.sh --skip-license --prefix=/usr/local

RUN python3 -m pip install cpplint==1.6.1

RUN git clone --depth 1 --branch "2.10" https://github.com/danmar/cppcheck.git cppcheck; \
    cd cppcheck; \
    cmake . -DCMAKE_BUILD_TYPE=Release; \
    cmake --build . --target install -j $(nproc) --config Release; \
    cd ..; \
    rm -rf cppcheck

RUN curl -o valgrind.tar.bz2 -L https://sourceware.org/pub/valgrind/valgrind-3.21.0.tar.bz2; \
    tar -xf valgrind.tar.bz2; \
    cd valgrind-3.21.0; \
    ./configure; \
    make -j $(nproc); \
    make install; \
    cd ..; \
    rm -rf valgrind-3.21.0

RUN python3 -m pip install conan==2.2.3; \
    conan profile detect

RUN apt-get install -y libc6-dbg

RUN apt-get install -y bison flex

RUN git clone --branch "Release_1_9_6" --depth 1 https://github.com/doxygen/doxygen.git; \
    cd doxygen; \
    cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release; \
    cmake --build . --target install -j $(nproc); \
    cd ..; \
    rm -rf doxygen

RUN apt-get install -y pkg-config parallel
